public class ColNamesAssoc {
	public static final int DATE_TIME = 0; //N
	public static final int APP_VERSION = 1; //N
	public static final int PACKAGE_NAME = 2;
	public static final int FILE_PATH = 3;
	public static final int PHONE_MODEL = 4;
	public static final int ANDROID_VERSION = 5; //N
	public static final int BOARD = 6;
	public static final int BRAND = 7;
	public static final int DEVICE = 8;
	public static final int BUILD_DISPLAY = 9; //N
	public static final int FINGERPRINT = 10;
	public static final int HOST = 11;
	public static final int ID = 12;
	public static final int MODEL = 13;
	public static final int PRODUCT = 14;
	public static final int TAGS = 15;
	public static final int TIME = 16; //N
	public static final int TYPE = 17;
	public static final int USER = 18;
	public static final int TOTAL_INTERNAL_MEMORY = 19; //N
	public static final int AVAILABLE_INTERNAL_MEMORY = 20; //N
	public static final int CUSTOM = 21;
	public static final int STACK_TRACE = 22;
	public static final int INITIAL_CONFIGURATION = 23;
	public static final int CRASH_CONFIGURATION = 24;
	public static final int DISPLAY = 25;
	public static final int USER_COMMENTS = 26;
	public static final int USER_CRASH_DATE = 27; //N
}